server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
  swagger-ui.path: /swagger-ui.html
