server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:9000/oauth2/jwks
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: customer-service
          uri: http://customer-service:8081
          predicates:
            - Path=/api/customers/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/api/products/**
          filters:
            - RemoveRequestHeader=Cookie
